version: "3"
services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    volumes:
      - postgres:/config
    ports:
      - 8190:8080
    environment:
      - EXTENSIONS=auth-totp
volumes:
  postgres:
    driver: local
    
