version: '3'
services:
  xteve:
    image: tnwhitwell/xteve:latest
    ports:
      - "34400:34400"
    volumes:
      - "/path/to/config:/config"
      - "/tmp/xteve:/tmp/xteve"
    user: "${PUID}:${PGID}"
